language: minimal

os: linux
sudo: required
services:
  - docker

env:
  global:
    - BACKPORTER="Julien Lamy <lamy@unistra.fr>"
    - DSC=http://deb.debian.org/debian/pool/main/o/odil/odil_0.10.0-9.dsc
    - ORIG=http://deb.debian.org/debian/pool/main/o/odil/odil_0.10.0.orig.tar.gz
    - DEBIANIZATION=http://deb.debian.org/debian/pool/main/o/odil/odil_0.10.0-9.debian.tar.xz
    - PATCH_DIR=${TRAVIS_BUILD_DIR}/patches

jobs:
  include:
    - env:
      - VENDOR=debian
      - VERSION=stretch
    - env:
      - VENDOR=debian
      - VERSION=buster

before_install:
  - docker run -di -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} --name ${VENDOR}_${VERSION} --rm ${VENDOR}:${VERSION}

script:
  # WARNING: this docker-specific files causes errors in d-shlibmove when 
  # calling `apt-cache --no-generate show PKG`
  - docker exec ${VENDOR}_${VERSION} rm -f /etc/apt/apt.conf.d/docker-clean
  - docker exec ${VENDOR}_${VERSION} ${TRAVIS_BUILD_DIR}/setup -u
  - docker exec -w /home/somebody -u somebody ${VENDOR}_${VERSION} wget ${DSC} ${ORIG} ${DEBIANIZATION}
  - docker exec -w /home/somebody -u somebody -e PATCH_DIR=${PATCH_DIR} ${VENDOR}_${VERSION} ${TRAVIS_BUILD_DIR}/prepare
  - docker exec -w /home/somebody -u somebody -e BACKPORTER="${BACKPORTER}" ${VENDOR}_${VERSION} ${TRAVIS_BUILD_DIR}/build
  - docker exec -w /home/somebody -u somebody ${VENDOR}_${VERSION} ${TRAVIS_BUILD_DIR}/check

after_success:
  - docker kill ${VENDOR}_${VERSION}
