matrix:
  include:
    - env:
        - VENDOR=debian
        - VERSION=stretch
    - env:
        - VENDOR=debian
        - VERSION=buster
before_install:
  - docker run -di -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} --name ${VENDOR}_${VERSION} --rm ${VENDOR}:${VERSION}

script:
  - docker exec -w ${TRAVIS_BUILD_DIR} -e WORKSPACE=${WORKSPACE} ${VENDOR}_${VERSION} ./setup

after_success:
  - docker kill ${VENDOR}_${VERSION}
