#! /bin/bash

set -euv

cd package

sudo apt-get install -y lintian

CHANGELOG="debian/changelog"
SOURCE_PACKAGE=$(dpkg-parsechangelog -l"${CHANGELOG}" -S Source)
VERSION=$(dpkg-parsechangelog -l"${CHANGELOG}" -S Version)

lintian -I -o ../${SOURCE_PACKAGE}_${VERSION}_*.changes
