#! /bin/bash

set -euv

# Get the source package from the repository. NOTE: if we need to modify the
# source code (e.g. modify the patch series) and not only the contents of the
# debian/ directory, using the official source package (*.dsc) will not work.
git clone ${REPOSITORY} package
cd package
git checkout ${TAG}

PATCH="${PATCH_DIR}/$(lsb_release -cs).patch"
if [ -e ${PATCH} ]; then
  patch --batch --strip=1 --input="${PATCH}"
fi

sudo mk-build-deps --tool "apt-get -y --no-install-recommends" --install debian/control

CHANGELOG="debian/changelog"
SOURCE_PACKAGE=$(dpkg-parsechangelog -l"${CHANGELOG}" -S Source)
VERSION=$(dpkg-parsechangelog -l"${CHANGELOG}" -S Version)

rm -f ${SOURCE_PACKAGE}-build-deps_*
