#!/bin/bash

set -euv

UNOFFICIAL_REPO="no"
while getopts "p:uh" OPT; do
  case ${OPT} in
    u) UNOFFICIAL_REPO="yes" ;;
    h) printf "Usage: %s: [-u]\n" $0
       exit 2;;
  esac
done

export DEBIAN_FRONTEND=noninteractive

APT_GET="apt-get -y --no-install-recommends"

apt-get update
apt-get upgrade -y
${APT_GET} install \
  adduser apt-utils curl devscripts dpkg-dev equivs git gnupg libwww-perl \
  lsb-release software-properties-common sudo

adduser --disabled-password --gecos '' somebody
chown -R somebody:somebody ~somebody
echo 'somebody ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

DISTRIB=$(lsb_release -cs)

if [ "${UNOFFICIAL_REPO}" = "yes" ]; then
  REPO="http://dl.bintray.com/lamyj/generic"
  EXISTS=$(curl -Lfs -o /dev/null "${REPO}/apt/dists/${DISTRIB}/Release" && echo "yes" || true)
  if [ x"${EXISTS}" = x"yes" ]; then
    curl -L "${REPO}/gpg.key" | apt-key add -
    add-apt-repository -s "deb ${REPO}/apt ${DISTRIB} main"

    apt-get update
  else
    echo "No repository for ${DISTRIB}"
  fi
fi
